[SNUS #54] 로드맵 성능 향상
snuhcs-course/swpp-2023-project-team-11 pull request #23
Opened 2023-11-11 16:01 UTC by jioon1830

JIRA: [SNUS-54: 로드맵 성능 향상](https://snusnec.atlassian.net/browse/SNUS-#54)

**Major Changes**

- 이제 get_topic_recommendation은 여러 topic을 리턴할 수 있습니다.
- 감정분석 API 요청 시 1000자 이상의 요청이 들어가지 않도록 입력값을 파싱합니다.

**Minor Changes**

- 바뀐 함수에 맞게 테스트 코드를 수정하였습니다.

**Tests for the Changes**

- 통과

**Comments**

-

2023-11-12 09:40 UTC, Kangji commented on fastapi/src/chatting/service.py
> +from sqlalchemy import func
한 줄로 합쳐주세요

2023-11-12 09:41 UTC, Kangji commented on fastapi/src/chatting/router.py
> +def get_topic_recommendation(chatting_id: int, limit: int | None = None, session: Session = Depends(get_session),
밑에 서비스 보면 limit의 default값이 None이 아니라 1이 되어야 할거같네요
`limit: int = 1`로 고쳐주세요

2023-11-12 09:43 UTC, Kangji commented on fastapi/src/chatting/service.py
> +        limit = 1
네 여기입니다. router에서 이미 default 처리를 했으니 여기서는 None이 안들어오겠네요.

`limit : int`로 하고 if문 지워주세요

2023-11-12 09:47 UTC, Kangji commented on fastapi/tests/chatting.py
> +        self.assertEqual(get_topics('C', 2, db)[0].topic, "I'm so sad" or "I'm so happy")
테스트가 잘못됐어요
이렇게 하면 첫 번째 assert문이랑 다를게 없습니다

여기서 테스트는 리턴한 리스트 전체를 확인해야되요.
그리고 리스트 값에 대한 테스트는 길이도 포함입니다.

2023-11-12 09:47 UTC, Kangji requested changes
이제 좀 더 디테일하게 리뷰합니당

2023-11-13 06:29 UTC, Kangji commented on fastapi/tests/chatting.py
> +        self.assertEqual(len(get_topics('B', 5, db)), 1)
다양한 조건 테스트 잘 넣어주셨네요 👍

2023-11-13 06:29 UTC, Kangji approved these changes
LGTM

conversation resolve시키고 머지해주세요

2023-11-13 07:00 UTC, sangin514 approved these changes
LGTM
회의때 논의했던 부분인 topic 여러개 리턴, 1000자 이상 파싱 잘 구현하신 것 같습니다

2023-11-13 07:50 UTC, closed without merging