[SNUS-63] non terminated chatting 있을 때 create chatting 막기
snuhcs-course/swpp-2023-project-team-11 pull request #27
Opened 2023-11-16 05:12 UTC by jioon1830

JIRA: [SNUS-###: Title](https://snusnec.atlassian.net/browse/SNUS-###)

**Major Changes**

- 두 대화대상자 간 채팅방이 존재할 경우 채팅방이 생성되지 않도록 하였습니다.

**Minor Changes**

- 주석 한 줄 작성

**Tests for the Changes**

- 

**Comments**

- refactor 브랜치로 병합하겠습니단..

2023-11-16 05:39 UTC, Kangji commented
테스트도 추가해주세요

Db 테스트 쪽에 동일한 채팅 만들면 에러나는거요

2023-11-16 07:14 UTC, jioon1830 commented
> 테스트도 추가해주세요
> 
> Db 테스트 쪽에 동일한 채팅 만들면 에러나는거요

테스트 추가한 것 확인부탁드림다

2023-11-18 09:15 UTC, Kangji commented
왜 500일까용 400으로 해주세요
Bad request가 맞습니다

2023-11-19 11:39 UTC, Kangji requested changes
* dev-server로 base branch 바꾸고 dev-server를 이 브랜치에 머지해주세요 지금 dev-server에 들어간 커밋들이 반영이 안되어있네요
* migration file 잘못 들어간 거 같은데 빼주세요
 
이렇게 두 개 고치고 머지하면 될 듯 합니다 수고하셨습니다

2023-11-19 11:39 UTC, Kangji commented on fastapi/alembic/versions/cd7492fda348_test.py
Migration File 이름이 test네요
다른 걸로 바꿔주세요

2023-11-19 11:39 UTC, Kangji commented on fastapi/alembic/versions/cd7492fda348_test.py
아니 그보다 얘가 지금 여기 들어가면 안될 거 같은데요
애초에 이번 PR은 Topic 이랑 관련이 없는데요

2023-11-19 13:14 UTC, Kangji approved these changes
Lgtm

2023-11-19 13:15 UTC, merged